# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a435372cb671404271c770873eae77329ac78bc07d7e86cc760f178520f6376d26a2ce917df661d501bd9690a289f1f327e1820add32abf7c3b7d88599bbc11c

test:
  secret_key_base: bd6b60f57c4eb48be46c4dfd5bf7b13a4c80e1bc6c77515ddec5f2d5c895bd73d90dff015da37c869f895d1e4cd390bb42275e5844395903c18fa081819f9da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
